name: release
on:
  push:
    tags:
      - 'v*' # push events for tags matching v for version (v1.0, etc)
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/devigned/go-twitter-action-v0:${{ env.RELEASE_VERSION }}
            docker.pkg.github.com/devigned/go-twitter-action-v0:latest


